# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-25 02:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20180825_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='subtotal',
            new_name='total',
        ),
    ]
